#!/bin/bash

installDir

# Code transformations
PARALLELIZATION_TECHNIQUES="-load ${installDir}/lib/ParallelizationTechnique.so -load ${installDir}/lib/DOALL.so"

# Set the command to execute
cmdToExecute="noelle-load ${PARALLELIZATION_TECHNIQUES} ${@}"
echo $cmdToExecute ;

# Execute
eval $cmdToExecute ;
