#!/bin/bash

installDir

# Set the command to execute
cmdToExecute="noelle-load -load ${installDir}/lib/LoopMetadata.so -enable-new-pm=0 -LoopMetadata ${@}"
echo $cmdToExecute ;

# Execute the command
eval $cmdToExecute 
